test macanum drive
XBOT-FTC/3231-IntoTheDeep pull request #3
Opened 2024-09-26 17:26 UTC by NormalDuck

Before issuing a pull request, please see the contributing page.

2024-09-26 18:32 UTC, NormalDuck commented
![image](https://github.com/user-attachments/assets/bc4a54cf-efe0-4394-99b8-ec1eb52559bb)
should I choose this option because I did a useless commit

2024-09-26 22:32 UTC, Jxwoon requested changes

2024-09-26 22:32 UTC, Jxwoon commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/src/JunjieMecanumDrive.java
> +            double turn = -gamepad1.right_stick_x;
Take another look at [mecanum-control-equations](https://gm0.org/en/latest/docs/software/tutorials/mecanum-drive.html#deriving-mecanum-control-equations).

2024-09-27 03:22 UTC, NormalDuck commented
force pushed the commit so I don't mess up with the external/samples

2024-10-02 20:23 UTC, closed without merging